name             'unwb'
maintainer       'Coddeys'
maintainer_email 'coddeys@gmail.com'
license          'All rights reserved'
description      'Installs/Configures unwb'
long_description 'Installs/Configures unwb'
version          '0.1.0'
