name             'unwb'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures unwb'
long_description 'Installs/Configures unwb'
version          '0.1.0'
